import { Poppins } from "next/font/google";
import NavBarComp from "@/components/NavBar";
import "./globals.css";
import FooterComp from "@/components/FooterComp";
const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarComp />
        {children}
        <FooterComp />
      </body>
    </html>
  );
}
